import { getPatients } from '../patient/repository';
import { PatientResponse } from '@/types';

export async function patientsResponse(): Promise<PatientResponse[]> {
  const patients = await getPatients();

  return patients.map<PatientResponse>(patient => {
    return {
      id: patient.id,
      birthday: patient.birthday,
      ethnicity: patient.ethnicity,
      gender: patient.gender,
      observations: patient.Observation.map(observation => {
        return {
          id: observation.id,
          date_testing: observation.date_testing,
          creatine: observation.creatine,
          chloride: observation.chloride,
          fasting_glucose: observation.fasting_glucose,
          potassium: observation.potassium,
          sodium: observation.sodium,
          total_calcium: observation.total_calcium,
          total_protein: observation.total_protein,
          creatine_unit: observation.creatine_unit,
          chloride_unit: observation.chloride_unit,
          fasting_glucose_unit: observation.fasting_glucose_unit,
          potassium_unit: observation.potassium_unit,
          sodium_unit: observation.sodium_unit,
          total_calcium_unit: observation.total_calcium_unit,
          total_protein_unit: observation.total_protein_unit,
        };
      }),
    };
  });
}

export function patientsResponseMock(): PatientResponse[] {
  return [
    {
      id: '1',
      birthday: '1990-05-15T00:00:00Z',
      gender: 'Male',
      ethnicity: 'Caucasian',
      observations: [
        {
          id: '101',
          date_testing: '2024-02-27T12:00:00Z',
          creatine: 0.8,
          chloride: 100,
          fasting_glucose: 80,
          potassium: 4,
          sodium: 140,
          total_calcium: 9.2,
          total_protein: 7.5,
          creatine_unit: 'mg/dL',
          chloride_unit: 'mmol/L',
          fasting_glucose_unit: 'mg/dL',
          potassium_unit: 'mmol/L',
          sodium_unit: 'mmol/L',
          total_calcium_unit: 'mg/dL',
          total_protein_unit: 'g/dL',
        },
        {
          id: '102',
          date_testing: '2024-02-27T12:00:00Z',
          creatine: 0.9,
          chloride: 98,
          fasting_glucose: 85,
          potassium: 4.2,
          sodium: 138,
          total_calcium: 9.5,
          total_protein: 7.8,
          creatine_unit: 'mg/dL',
          chloride_unit: 'mmol/L',
          fasting_glucose_unit: 'mg/dL',
          potassium_unit: 'mmol/L',
          sodium_unit: 'mmol/L',
          total_calcium_unit: 'mg/dL',
          total_protein_unit: 'g/dL',
        },
        {
          id: '103',
          date_testing: '2024-02-27T12:00:00Z',
          creatine: 0.7,
          chloride: 102,
          fasting_glucose: 78,
          potassium: 3.8,
          sodium: 142,
          total_calcium: 9.0,
          total_protein: 7.2,
          creatine_unit: 'mg/dL',
          chloride_unit: 'mmol/L',
          fasting_glucose_unit: 'mg/dL',
          potassium_unit: 'mmol/L',
          sodium_unit: 'mmol/L',
          total_calcium_unit: 'mg/dL',
          total_protein_unit: 'g/dL',
        },
      ],
    },
    {
      id: '2',
      birthday: '1985-08-21T00:00:00Z',
      gender: 'Female',
      ethnicity: 'Asian',
      observations: [
        {
          id: '104',
          date_testing: '2024-02-27T12:00:00Z',
          creatine: 1.2,
          chloride: 105,
          fasting_glucose: 88,
          potassium: 4.5,
          sodium: 137,
          total_calcium: 9.8,
          total_protein: 8.0,
          creatine_unit: 'mg/dL',
          chloride_unit: 'mmol/L',
          fasting_glucose_unit: 'mg/dL',
          potassium_unit: 'mmol/L',
          sodium_unit: 'mmol/L',
          total_calcium_unit: 'mg/dL',
          total_protein_unit: 'g/dL',
        },
        {
          id: '105',
          date_testing: '2024-02-27T12:00:00Z',
          creatine: 1.0,
          chloride: 100,
          fasting_glucose: 90,
          potassium: 4.8,
          sodium: 135,
          total_calcium: 10.0,
          total_protein: 8.2,
          creatine_unit: 'mg/dL',
          chloride_unit: 'mmol/L',
          fasting_glucose_unit: 'mg/dL',
          potassium_unit: 'mmol/L',
          sodium_unit: 'mmol/L',
          total_calcium_unit: 'mg/dL',
          total_protein_unit: 'g/dL',
        },
        {
          id: '106',
          date_testing: '2024-02-27T12:00:00Z',
          creatine: 1.1,
          chloride: 98,
          fasting_glucose: 92,
          potassium: 4.2,
          sodium: 139,
          total_calcium: 9.6,
          total_protein: 7.5,
          creatine_unit: 'mg/dL',
          chloride_unit: 'mmol/L',
          fasting_glucose_unit: 'mg/dL',
          potassium_unit: 'mmol/L',
          sodium_unit: 'mmol/L',
          total_calcium_unit: 'mg/dL',
          total_protein_unit: 'g/dL',
        },
      ],
    },
    {
      id: '3',
      birthday: '1978-12-10T00:00:00Z',
      gender: 'Non-Binary',
      ethnicity: 'African American',
      observations: [
        {
          id: '107',
          date_testing: '2024-02-27T12:00:00Z',
          creatine: 0.8,
          chloride: 103,
          fasting_glucose: 82,
          potassium: 4.0,
          sodium: 141,
          total_calcium: 9.3,
          total_protein: 7.7,
          creatine_unit: 'mg/dL',
          chloride_unit: 'mmol/L',
          fasting_glucose_unit: 'mg/dL',
          potassium_unit: 'mmol/L',
          sodium_unit: 'mmol/L',
          total_calcium_unit: 'mg/dL',
          total_protein_unit: 'g/dL',
        },
        {
          id: '108',
          date_testing: '2024-02-27T12:00:00Z',
          creatine: 0.9,
          chloride: 101,
          fasting_glucose: 84,
          potassium: 4.1,
          sodium: 138,
          total_calcium: 9.7,
          total_protein: 7.9,
          creatine_unit: 'mg/dL',
          chloride_unit: 'mmol/L',
          fasting_glucose_unit: 'mg/dL',
          potassium_unit: 'mmol/L',
          sodium_unit: 'mmol/L',
          total_calcium_unit: 'mg/dL',
          total_protein_unit: 'g/dL',
        },
        {
          id: '109',
          date_testing: '2024-02-27T12:00:00Z',
          creatine: 0.7,
          chloride: 104,
          fasting_glucose: 80,
          potassium: 3.9,
          sodium: 140,
          total_calcium: 9.1,
          total_protein: 7.4,
          creatine_unit: 'mg/dL',
          chloride_unit: 'mmol/L',
          fasting_glucose_unit: 'mg/dL',
          potassium_unit: 'mmol/L',
          sodium_unit: 'mmol/L',
          total_calcium_unit: 'mg/dL',
          total_protein_unit: 'g/dL',
        },
      ],
    },
  ];
}
